### ISSUE TITLE
Pid version

### ISSUE THREAD

**Issue by JackBekket** [MoonSHRD/p2chat-android#3]
https://github.com/MoonSHRD/p2chat-android/blob/master/pkg/main.go#L203
Pid in android - "chat/1.0.0"

https://github.com/MoonSHRD/p2chat/blob/master/cmd/flags.go#L19
Pid in desktop - "/moonshard/1.0.0"

**Comment by ChronosX88** [comment]
I set a custom protocol id (https://github.com/MoonSHRD/SimpleMdns/blob/b4249ffc61ca9e63b71b6173f63daabf6722e5e9/app/src/main/java/com/example/simplemdns/AppHelper.java#L12).
