### ISSUE TITLE
Complete android port

### ISSUE THREAD

**Issue by JackBekket** [MoonSHRD/p2chat-android#5]
Fix minor bugs we found so far

**Comment by JackBekket** [comment]
The following module functional should be implemented:

- discover devices in network and auto-subscribe them into serviceTopic
- exchange topic list across the network using serviceTopic
- read and send messages to a specific topics
- get peers subscribed on specific topics
- been able to blacklist peer (`pubsub.blacklist(peer.ID))`)


The following functions (exported) should be implemented:

- get network topics
- ask network topics
- send message to a topic
- get messages from a topic
-  **get peerlist**
- **been able to blacklist peer**

Note - this functions should be invokable from Java side, because we will tether interface on react native to the Java.

**Comment by JackBekket** [comment]
Still missing

- new topic
- subscribe to a topic by given string
- unsubscribe from a topic by given string

**Comment by ChronosX88** [comment]
Done.
